project_name: 'SuperGamer'
game_name: 'Slay the Spire'
run_name: 'macbook run 11 aug'
close_explore: False
close_reflexion: False
close_reset: False
is_base: False

result_path: 'results'

teacher_type: 'Random' # Human or AI or Random

brain:
  base_model: 'claude-3-7-sonnet-20250219' # gpt-4o or claude-3-7-sonnet-20250219
  evaluate_model: 'gpt-4o'

  uct_c: 5.0
  uct_threshold: 0.0

detector:
  sam_weights: 'weights/sam_vit_b_01ec64.pth'  # sam_vit_b_01ec64 or sam_vit_h_4b8939
  sam_type: 'vit_b'     # vit_h or vit_b
  clip_model: 'ViT-B/32' # ViT-B/32, ViT-B/16, ViT-L/14, RN50

eye:
  width: 1280
  height: 720

long_memory:
  sim_threshold: 0.9